name: Laravel CI/CD Pipeline

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, xml, ctype, json, bcmath, curl
        tools: composer, phpunit

    # Cache Composer Packages
    - name: Cache Composer Packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.composer/cache/files
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-


    # Install Dependencies
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Generate Laravel key
    - name: Generate key
      run: php artisan key:generate

    # Directory Permissions
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Setup Environment File
    - name: Setup Environment File
      run: cp .env.example .env

    # exit maintenance mode
    - name: deploy app
      with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
      run: php artisan up

    # test cache
    - name: Test Cache Operations
      run: php artisan cache:clear && php artisan config:clear && php artisan route:clear && php artisan view:clear && php artisan cache:clear

    # Execute Tests
    - name: Execute Tests
      run: vendor/bin/phpunit
